### ISSUE TITLE
Translation 

### ISSUE THREAD

**Issue by CBID2** [mdn/curriculum#16]
### Please describe your problem or observation

The curriculum is written only in English. While wanting to cater to an English-speaking audience is helpful, it could make it difficult for non-English speakers to understand the content.

### Describe the solution you'd like to see

Add some translations in the future.

**Comment by chrisdavidmills** [comment]
Hi @CBID2!

While we are intending to have the initial release only in English, we are also intending to explore the possibility of releasing translations in the future.

**Comment by veryhappy111** [comment]
Come to the Chinese version
