### ISSUE TITLE
Is there more information available about the research?

### ISSUE THREAD

**Issue by Elchi3** [mdn/curriculum#17]
### Please describe your problem or observation

Thanks for making this work available for feedback.

It seems that prior to open sourcing this work, some research was done:

> The curriculum is an outcome of a research project conducted by the MDN team in early 2023. We asked students, new web developers, technical hiring managers, and web education professionals about their expectations around learning front-end web development — on MDN and elsewhere. The key outcomes of this research were:

> Students expect more structured guidance on what topics to learn and when.
> All groups cited a lack of "soft skills" (like teamwork, research, and critical thinking) and knowledge of best practices (such as accessibility and privacy) in potential new hires as key problems in the industry.

Is it possible to get more insight into this process and more detailed results of this research? I'm trying to figure out if the MDN Curriculum is more research-based or more opinion-based. What would you say?

I'm currently working on figuring out a curriculum for web developers to learn about web security. I see that this curriculum contains a section about security and privacy (https://github.com/mdn/curriculum/blob/main/curriculum/3-extensions/5-security-and-privacy.md) and I would like to understand how it was decided which topics are important for this curriculum. 

For my work, I'm basing my thoughts around data gathered by this survey: https://github.com/web-platform-dx/developer-research/blob/main/mdn-short-surveys/2023-05-15-security-dx/interpretation.md and I'm talking to SMEs for web security.
Do you have other public data points for me? Did you work with SMEs to figure out what is important to learn with regards to web security?

(I'm picking on security here, but I'm interested in the research process here generally. I'd have similar questions about the performance section which I'm also looking into, for example.)

**Comment by chrisdavidmills** [comment]
Hello @Elchi3! To give you some answers to your questions:

I have shared your ask with the Mozilla folk to see if there is interest in publishing the research. At a high level, the curriculum has elements of research and opinion. The research mentioned above mainly served to gather some evidence in support of the curriculum, and some high-level ideas of what web developer skillsets are missing, where we could do better, etc. 

It also served to provide insight into some of the lower-level details on topics to include, but these were largely arrived at via a combination of:

- Opinion (mine)
- The collective knowledge of MDN
- Consulting with domain experts on what to include, which was particularly useful for areas like performance and security/privacy.

HTH.
