### ISSUE TITLE
Curriculum README.md - link to curriculum introduction needs correcting

### ISSUE THREAD

**Issue by Jo-with-vision** [mdn/curriculum#27]
### Please describe your problem or observation

The link to read more about the target audience mentioned in [Target audience and purpose](https://github.com/mdn/curriculum/blob/main/README.md#target-audience-and-purpose) currently takes you to [https://github.com/mdn/curriculum/tree/main/curriculum](url). 

The actual 'introduction' with information about the target audience is contained within [1-about.md](https://github.com/mdn/curriculum/blob/main/curriculum/1-about.md).

![Screenshot 2024-01-31 153228](https://github.com/mdn/curriculum/assets/157862235/b30d8f9c-4bab-4ac3-a979-0ae9e9c4ee21)

### Describe the solution you'd like to see

Suggestion: update the README.md link to take you straight to [target-audience](https://github.com/mdn/curriculum/blob/main/curriculum/1-about.md#target-audience), and re-word paragraph to reflect user will be taken to the target-audience section of the about.md (unless about.md should actually be renamed to Introduction.md?)

Thanks

**Comment by chrisdavidmills** [comment]
This is kind of out of date now the actual curriculum site is published, but it is still good to not have broken links lying around! I've added a small fix for this one in a PR I am currently working on.
