### ISSUE TITLE
The link can not open https://documentation.divio.com/ 

### ISSUE THREAD

**Issue by frankfancode** [mdn/curriculum#46]
### Please describe your problem or observation
https://developer.mozilla.org/en-US/curriculum/getting-started/soft-skills/
![page-can-not-open](https://github.com/mdn/curriculum/assets/2646397/0fd9617d-80a5-4143-8b06-c03dc9b9a887)
The link `[types of documentation](https://documentation.divio.com/)` can not open

**Comment by chrisdavidmills** [comment]
Hi there @frankfancode! I've just tested this link on several desktop and mobile browsers, and it seems to work for me. Is there a specific set of circumstances under which the link fails?

**Comment by frankfancode** [comment]
@chrisdavidmills 
Thank you for your reply. After changing the VPN IP, It works. 
Before making the change, I could access other pages on divio.com but not this one.
