### ISSUE TITLE
No redirect to curriculum without locale

### ISSUE THREAD

**Issue by MichaelKohler** [mdn/curriculum#47]
### Please describe your problem or observation

https://developer.mozilla.org/en-US/curriculum/ works great, but https://developer.mozilla.org/curriculum/ does not.

### Describe the solution you'd like to see

It should redirect.

**Comment by 23bffd855647cc-2** [comment]
https://4.bing.com/ipv6test/test

**Comment by fiji-flo** [comment]
@MichaelKohler I missed this but it should work now?

**Comment by MichaelKohler** [comment]
It indeed does!

**Comment by 23bffd855647cc-2** [comment]
u

**Comment by 23bffd855647cc-2** [comment]
Cs
