### ISSUE TITLE
Incorrect numbering in section 8 Design for developers.

### ISSUE THREAD

**Issue by Yazan-Sharaya** [mdn/curriculum#56]
### Module number

8.3 Design briefs

### Please describe your issue

The main issue is that "8. Design for developers" subsections are incorrectly numbered as 9.x instead of 8.x in both the "In this module" sidebar and the headings
 
I also think that the last subsection (Design briefs) abruptly ends without any supplementary links.

One last thing (this is just a nitpick, sorry), the "Module number" placeholder text when you open an issue incorrectly numbers "How the web works" as 2.1 instead of 1.1 :)

**Comment by chrisdavidmills** [comment]
Thanks for reporting this @Yazan-Sharaya!

I have submitted a PR to fix the numbering issue.

@fiji-flo, just flagging up the "One last thing..." nitpick in case you want to investigate it further.

**Comment by chrisdavidmills** [comment]
Fixed by https://github.com/mdn/curriculum/pull/58
