### ISSUE TITLE
404 Not Found

### ISSUE THREAD

**Issue by xionnon** [mdn/curriculum#62]
https://github.com/mdn/curriculum/blob/81240ab65ac8b9e79fbb112361164e7e9701b2ce/curriculum/3-core/8-design-for-developers.md?plain=1#L23

it should be <https://designforweb.org/vis/chapter2-typography/typelab-by-HannahBoom/>?

**Comment by pransh15** [comment]
Hi @xionnon! 👋 
Thanks for opening this issue. The link is incorrect and needs updating. Would you like to open a PR for the same? 😄

**Comment by caugner** [comment]
This was meanwhile fixed by https://github.com/mdn/curriculum/pull/63.
